# Project
site_name: PoC Documentation
site_description: PoC Documentation
site_author: Diego Dalben

nav:
  - Getting started:
    - Overview: ./getting-started/overview.md

# Theme configuration
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
